apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cu-delaparra-local-tls
  namespace: default
spec:
  secretName: cu-delaparra-local-tls
  dnsNames:
    - cu.delaparra.local
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  usages:
    - digital signature
    - key encipherment
    - server auth