apiVersion: apps/v1
kind: Deployment
metadata:
  name: compute-unit-deployment
  namespace: hyperbeam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compute-unit
  template:
    metadata:
      labels:
        app: compute-unit
    spec:
      containers:
        - name: compute-unit
          image: 'foxoffire33/compute-unit'
          ports:
            - containerPort: 6363
          volumeMounts:
            - name: secrets-volume
              mountPath: /secrets
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: compute-unit-pvc
        - name: secrets-volume
          secret:
            secretName: hyperbeam-wallet