apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: compute-unit-ingress
  namespace: hyperbeam
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-buffers: "4 256k"
    nginx.ingress.kubernetes.io/proxy-busy-buffers-size: "256k"
    nginx.ingress.kubernetes.io/proxy-max-temp-file-size: "0"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/use-regex: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - cu.delaparra.local
      secretName: cu-local
  rules:
    - host: cu.delaparra.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cu-service
                port:
                  number: 6363
