apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hyperbeam
resources:
  - namespace.yml
  - secret.yaml
  # Postgres
  - Postgres/deployment.yaml
  - Postgres/service.yaml
  - Postgres/pvc.yaml
  - Postgres/pv.yaml
  - Postgres/secret.yaml
  # HyperBeam
  - HyperBeam/deployment.yaml
  - HyperBeam/service.yaml
  - HyperBeam/pvc.yaml
  - HyperBeam/ingress.yaml
  - HyperBeam/certificate.yaml
## Compute Unit
#  - ComputeUnit/deployment.yaml
#  - ComputeUnit/service.yaml
#  - ComputeUnit/ingress.yaml
#  - ComputeUnit/pvc.yaml
#  - ComputeUnit/certificate.yaml