apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smartlabel
resources:
# Postgres
  - HyperBeam/secret.yaml
  - HyperBeam/deployment.yaml
  - HyperBeam/service.yaml
  - HyperBeam/pvc.yaml