apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperbeam-deployment
  namespace: hyperbeam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyperbeam
  template:
    metadata:
      labels:
        app: hyperbeam
    spec:
      containers:
        - name: hyperbeam
          image: 'foxoffire33/hyperbeam:latest'
          ports:
            - containerPort: 8734
            - containerPort: 6363
          env:
            - name: HB_STORE_PATH
              value: "/data"
            - name: HB_KEY
              value: "/secrets/wallet.json"
          volumeMounts:
            - name: data-volume
              mountPath: /data
            - name: secrets-volume
              mountPath: /secrets
            - name: config-volume
              mountPath: /app/HyperBEAM/config.flat
              subPath: config.flat
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: hyperbeam-pvc
        - name: config-volume
          secret:
            secretName: hyperbeam-config
        - name: secrets-volume
          secret:
            secretName: hyperbeam-wallet