apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperbeam-deployment
  namespace: hyperbeam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyperbeam
  template:
    metadata:
      labels:
        app: hyperbeam
    spec:
      containers:
        - name: hyperbeam
          image: ${DOCKER_IMAGE}
          ports:
            - containerPort: 8734
          env:
            - name: HB_STORE_PATH
              value: "/data"
            - name: HB_KEY
              value: "/secrets/wallet.json"
          volumeMounts:
            - name: data-volume
              mountPath: /data
            - name: secrets-volume
              mountPath: /secrets
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: hyperbeam-pvc
        - name: secrets-volume
          secret:
            secretName: hyperbeam-wallet