version: '3.8'
services:
  hb-service:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: HyperBeam
    ports:
      - "8734:8734"
    volumes:
      - ./data:/data
      - ./secrets:/secrets:ro
    environment:
      HB_STORE_PATH: /data
      HB_KEY: /secrets/wallet.json
    restart: unless-stopped
