apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hyperbeam-ingress
  namespace: hyperbeam
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"       # Long AO requests
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"             # Large TX payloads
    nginx.ingress.kubernetes.io/use-regex: "true"                  # Preserve ~device@1.0 paths
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - hyperbeam.delaparra.local
      secretName: hyperbeam-tls-secret
  rules:
    - host: hyperbeam.delaparra.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hyperbeam-service
                port:
                  number: 8734