apiVersion: v1
kind: Secret
metadata:
  name: hyperbeam-wallet
type: Opaque
data:
  wallet.json: eyJkIjoiem9CeUpITTZWZ3FwQThfWEpUQ3NydEFoSzI1UUpkclBNNVAwbGJlWDBnTmdyU0RFOGlS
  bVhhREtnUWZpWWg5Qi14LTBnbG1BeEtjMlBpOUFTR242b2JvOU1ZU0hrZTg0eS1pNGpxRFZwWi1I
  Q1prVFRUZF94Ym5YNExJRFpENEItdDR1a1lJWnhLTE1XRTlvNUpMcHFwdXZhM3Jwc1F3T2dmRDBi
  d2sxbHlBLWxoOWhhd09HSHhDWFJPS3lTNDFvWnBpRzk3RnluRVNfd1FuOU1ST3RNVm80bTg5TzRY
  NDVYaEt0YmxWXzIyN0lRSnUyT3pkOWVVX3FlUExvQzVUNG00dElVZ3lUZzI0di1TTEhrNEpWNXFo
  ZXRtNzdHanhoYU9XMUtIby1jSndtYWhmLTB5MW4xMWJLMjZmbzBDOVVOdS1kNHVqd1JlM0puNFRv
  M0RCZjBYaExuTXRBTjUtV1BlQ2VLQ0tRbW5RV05QTE54VC1lRWkxT2xCb0s2RUZLU1l3VGx6QUU5
  Z0NyR0pLaUlPZ19YejZwWFpJT2tkMHN0akYxTTRISEVyaTkwWHpZWVNMY2pLT1RheTRZcXNhRWxk
  RGhKeEt4Q1dwTzRTMjBQOVNCNUJHQnNMeWNzb2tnRVBEZnZxR1AyaWd2b1dsT0VJWVJZUjJ2MVY1
  SmkwUXJqaEs1NGxWR0RubjY3dzA4UGlqdkNETlpmdk5aVmlmX2FXNDU3U2dlWUJ0dXVOZHQ0VlNo
  VWZLeHJXdDl2anZPckNKTDB6dnRxRl9YQXZNX2tQNG9Db240dU8xc2VJbnFlVHYxU3pEREF1TlR3
  a3A1ME5BS2o2RW9vNy0zaVJwdC1PNVVzWUpfZW1IbHJVYTFMN054NVlWakVDRFFidTRQcTVoTmJL
  TTBJcFUiLCJkcCI6Ii1DNE43bVBqQ0JDTXI3bDk1RlUzNDRCWWw2ZngtM1llVzBTdmw4SDRHM0tv
  WUVvb3M2ejJFYVVhMnhDdy1EaEtXdlUtZlQwTy1sOXEwc2NvWEF4VU5jZElWZndlWVJDWE8tdEFl
  ZVo0MEpCa0NyM2daTDBkdDN6RWxTZXdSQ016VEw5TTZ0YlZMVllWV0RCcG41d2oxWnRQV29zTjBj
  MGNha0xySGJkSk9QLU9GVm5nbms4TmZiOWFUZjBJSjhVNjFCQ3BpZDVKMHlBZFVQRmRwNWlub3h3
  TW53WnBnQnNneElxbFlVTVR0OVg3QXFFX0dDaE5PWEtfeTZ4T05QSEhxeVJ6VEwyejE2RVpSdHBU
  VU1ldEdIQWxlU1F0RHNremxRN3ZsWXBJMHp2QzlWNzJObUVUaEtQLTJPWkJDODJVY1hMSGtLZWg3
  MUM5R0tSWE94NXQ4USIsImRxIjoiSjdOUlhjXzl6eGtVcDNzOGpuMHZpS3lnaEo1dFR1NVlOWkRy
  N2tpcGM3LV8zNEQyTmtkb0Y5LVd0X056bDc4ZHBuSkVVekJkSlF1M3ZwN3FEeVg4ZkR6SjVCeGht
  MjhSbVhaOUxyRVJhd1FVeFhWX1doZkhlbVBQbU5kelI0UFZ0SkpZckVrOUFyN0U1aVc0QUJMQTBl
  U1lIbGRHdTFzWThMUDVJWFc3OVZrbWx1R180anVzN1pldHRJb2c0T1hzNTE2UU1SREU5WXpqbnFI
  UUFWdFFvWWlnQXE2OEdCcmQ2dEkxN0R4OGhJNldZTVdPV3VSQ19Wd25rWkRxcDJlVHliM2UxRzJs
  QUY4Snlud2hiNmpubmUyTGd5cUNtejZGeGlMM0QxV3p0akRlQTJPZTAyMGFxSjVpY0FNVERpSU1U
  N01MTURld0hxbHBsQXZCNFdGeUx3IiwiZSI6IkFRQUIiLCJleHQiOnRydWUsImt0eSI6IlJTQSIs
  Im4iOiI4SDlQSmJ1eEtIMENWZjVyMUw2eDVwTEpPc1Q0dDZoWmp1M1lQUEZNbkxWOXJ6aVJfVmNi
  V0g0a2FWRWlHeE5VaWx3SG1QV2pLTnRTenFrNy1LUDRCME82bUhRSGI0S2lrOEhwLURWN2RJSFNC
  OGVja0ZWTE9qbGZrLUhMR2p1WW9IWkFLNXBpZDZPR19HSFp5NW5RMlhFd3BvTmc2LTZlcllpRktt
  YmwxcnA3U1UtZm1ta1F5T3pxMjNTcGJLRlZuTVJRX3ZFaFA4cU9OV2d6bnVMMFNsVUVKMUxHMmZX
  ckF5SjNxTFJBVktWeUd5aXJhVERwZ2ZKUzc5REQzWnktekVVY2tpQkM1R2hOY1lDd0dsSlNFRndf
  TVZnbUV0dmRHcDBZVVF2MjB0Q2lJSmU3RlkwRWpFLVY0dDYtR0c0Y3BLNmZSLUNiUUc1cTJZTGV1
  aXVKVVNERjB2eWpzLTU0NWl2QkxGQ01TZXhweWlJQkJVQTYzdExtZmdKdEI1UmlCMThRR3BlLW1r
  QUN0S2FjSlNfRGM4WjNZcVVZVmZFdFF6NTAzYk1EMFpXbElTd0VVSERXQWpHMlZnZUtaR1BDNzF1
  a0M1SEZaUGZud0FxYzNYVmowckZxbHhEUndza0NHazdMOXRReWotdnBZNV9tTVRTd0t4c21ZZkts
  V2oxSDZEVlJQYkxlRGhNTFpSdDVtQVE2aVJpYmJxdGQ5RkVfY1N3VHAta2U5NWh1QklVblNMdHZU
  RndqMWRCNUZEWGkwR3JQX0g3aVNQaVcyYW5zczFsMVdNNFBPVnM0Y3g1alJxQnlMWjEtazBQSzJr
  d1M3N1UxR3ZoZTBZbjZSQW1URU93bU9ZVDl2Y3U4T205WWkzSUpaUG9jS1AyVW5OVVVJX21Vd2xY
  bXlnRSIsInAiOiItNmV1TzdTbld1eW9jeHlxMlNIYnlOVnR3NXRGOG1nWmF5Vm03X0RhWUktX2J2
  SlFxckJvc0Vtd3VEWUszMDNOVUVNR0lCenliNGctVGpZcWFQZFp0dWxtVG9uSzhkVHdQTmxiOGRU
  cWsyR2xhMFMxeEh0Vl9EMDBNajJ2UHFpN1JUOGdsVEthdG4tMXA3NFpHS1RKV01DTTUydWNYUU5p
  S2dPeWJybGxueUs1dEszOFcxSWw0cFQyRWtma0FmUkpPLWNGWlphUFc2V1JHWENENnN0dGxzQUZ6
  NWdab1FVN1dUNk8xRVlNVm5zVmZIdlhDTDVGUm1COS0wdDhjSzNpcFVPMWlrRTIzeGpBVHdxNEJP
  eGdsU3dCVGVTMTFRNmRfQ1RtOUFlWk1uN21UbWJHZ2xPQXhHMGs1eldQRTByQU5jVVpBOFNBZkty
  bjdGd1ZDY0FYWXciLCJxIjoiOUtaUHRDalE2eHB5MVp1RzBWRzVJVmZFNlJVb05UemJKUG9YSXpz
  V3pqbWVOQ2lzaHFXR09xMjJ3M2Jnd3BBSGM1ejlFd0pMZVZFZG85N01PVXFLWGo4U0FNYmZJMVJB
  UEVidUdGM0ktWU5CcmhFMDRBbElBSGJkVkNlc05OYndlOU1wSjBJbjBGVk0tb0NrTmVQYm5wZV9M
  SXF0YlJCTnNxZ0R5aVlkZlZHVG9ZMC01ZmZYLWNHS3JsSlBkZVcxamRjZHVDVlB0Vk9nMjZtWlNv
  aHZ6dXlvM21QZC03QzFpaG5lNDJfZzFCaWZvR0wxLVJVUFJybTFxUjBia2M1eEJlXzdid0ZERm1s
  WE13Mi1MdjdtUFZCY2M1ZDU2b0hkc0tGT3ZyWmpfWUt3V294TExTSGUzdm1aTFI5TFpaV0V2Mzg5
  TWlsMWpLTm5JaGZnaXJ0UVN3IiwicWkiOiJBVWpHcDNpc0RqUUtNV1pES2ExMlpZRGp2bGo0NFRL
  TGIzV2lCeDBiY1MtQm1fSjIzcU1yaHpLLXhWTXFhY2xvNWloM2FzZU5fVkhYODJxMnZNajhEbVUy
  clp2bl9BYWQ3LW42VkpnLVVpenhmUU53RWpJcVI0RjR4WnZfYVZKR0g4TldNcWJqcHJYazVoa1Bi
  eDhINGhQbEx4NFU3cXNuMnNiakpJQ1F6YjhDTDNfQ2tMYm5LTVJiTGpnZTZOQUtReFhyTk5KVlp2
  WThKNXFLaGRpTE1sOU9WbDc4WlNWTktpSkgxZlRiNk9aakFtMXZ4bjBqNnNfUDZ5TmFWQmNCQ3N6
  TjJXblItNWtnUldnZGJvakZtNmEyMVhCY1pBVU9pTS1TbC1ZUGVDOW9na2tfUG5JVzF1Sm1WcEg5
  X1N6a1huWWJLcGlfaWZLNmxPRDEySnhVSmcifQ==;
---
apiVersion: v1
kind: Secret
metadata:
  name: hyperbeam-config
type: Opaque
stringData:
  config.flat: |
    {hb_key, "/secrets/wallet.json"}.
    {hb_store_path, "/data"}.
    {hb_port, 8734}.
    {hb_peers, ["hyperbeam-peer1.arweave.net:8734", "hyperbeam-peer2.arweave.net:8734"]}.
    {hb_http_enabled, true}.
    {hb_healthcheck_path, "/~meta@1.0/info"}.
